receivers:
  otlp:
    protocols:
      grpc:
      http:


processors:
  batch:
    timeout: 5s

exporters:
  zipkin:
    endpoint: "http://zipkin-collector:9411/api/v2/spans"
    format: proto
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [batch]
