version: "3.6"

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      container_name: pocdb
      MYSQL_DATABASE: 'pocdb'
      MYSQL_ROOT_PASSWORD: 'root'
      #MYSQL_USER: 'user'
      #MYSQL_PASSWORD: 'password'

    volumes:
      - ./pocdb:/var/lib/mysql
